language: java
arch:
  - amd64
  - arm64
jdk:
  - openjdk8
before_install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then 
    export MVN_HOME=$HOME/apache-maven-3.6.3;
    wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P $HOME; 
    tar xzvf $HOME/apache-maven-3.6.3-bin.tar.gz -C $HOME;
    export PATH=$MVN_HOME/bin:$PATH;
    mvn --version;
    fi
  - pip install --user codecov
after_success:
  - codecov
branches:
  except:
    - appveyor
